query products(
  $category: String!
  $tag: String!
  $start: Int
  $limit: Int
  ){
    products(
    start: $start
    limit: $limit
     
    where: {
      category: { name: $category }
      tags: { name_contains: $tag }
    }
  ){
      id,
    image{
      formats
    },
    name
  }
  }