query productCount($category: String!, $tag: String!) {
  productsConnection(
    where: {
      category: { name: $category }
      tags: { name: $tag }
    }
  ) {
    aggregate {
      count
    }
  }
}